Filmy/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Filmy.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter customer's name.")]
        [StringLength(255)]
        public string Name { get; set; }

        public bool IsSubcribedToNewsletter { get; set; }

        [Required]
        [Min18YearsIfAMember]
        [Display(Name = "Date of Birth")]
        public DateTime Birthdate { get; set; }
        public List<Movie> MovieLibrary { get; set; }
    }
}

Filmy/Controllers/Api/CustomersController.cs
using Filmy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Filmy.Controllers.Api
{
    public class CustomersController : ApiController
    {
        // GET /api/customers
        public IEnumerable<Customer> GetCustomers()
        {
            return CustomersMockData.GetCustomers();
        }

        public Customer GetCustomerById(int id)
        {
            var customer = CustomersMockData.CustomerCollection.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return customer;
        }

        // POST /api/customers
        [HttpPost]
        public Customer CreateCustomer(Customer customer)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            CustomersMockData.AddCustomer(customer);
            return customer;
        }

        // PUT /api/customers/1
        [HttpPut]
        public void UpdateCustomer(int id, Customer customer)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var customerInDb = CustomersMockData.CustomerCollection.SingleOrDefault(c => c.Id == id);

            if(customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            customerInDb.Name = customer.Name;
            customerInDb.IsSubcribedToNewsletter = customer.IsSubcribedToNewsletter;
            customerInDb.Birthdate = customer.Birthdate;
        }

        // DELETE /api/custoemrs/1
        [HttpDelete]
        public void DeleteCustomer(int id)
        {
            var customerInDb = CustomersMockData.CustomerCollection.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            CustomersMockData.CustomerCollection.Remove(customerInDb);
        }
    }
}

Filmy/Controllers/CustomersController.cs
using Filmy.Models;
using Filmy.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Filmy.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var selectedCustomer = CustomersMockData.GetCustomers().FirstOrDefault(c => c.Id == id);

            if (selectedCustomer != null)
                return View("Details", selectedCustomer);
            else
                return HttpNotFound();
        }

        public ActionResult New()
        {
            return View("CustomerForm");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View("CustomerForm");
            }

            if (customer.Id == 0)
            {
                customer.MovieLibrary = new List<Movie>();
                CustomersMockData.AddCustomer(customer);
            } else
            {
                var customerInDb = CustomersMockData.GetCustomers().Single(c => c.Id == customer.Id);
                int indexOfCustomer = CustomersMockData.CustomerCollection.IndexOf(customerInDb);

                customerInDb.Name = customer.Name;
                customerInDb.IsSubcribedToNewsletter = customer.IsSubcribedToNewsletter;
                customerInDb.Birthdate = customer.Birthdate;

                CustomersMockData.CustomerCollection[indexOfCustomer] = customerInDb;
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var customer = CustomersMockData.CustomerCollection.SingleOrDefault(c => c.Id == id);

            if (customer != null)
                return View("CustomerForm", customer);
            else
                return HttpNotFound();
        }

        [HttpPost]
        public ActionResult DeleteMovie(int id, int customerId)
        {
            var customer = CustomersMockData.CustomerCollection.SingleOrDefault(c => c.Id == customerId);
            var movie = customer.MovieLibrary.SingleOrDefault(m => m.Id == id);

            customer.MovieLibrary.Remove(movie);

            return RedirectToAction("Index");
        }

    }
}

Filmy/Views/Customers/CustomerForm.cshtml
@model Filmy.Models.Customer

@{
    ViewBag.Title = "CustomerForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <h2>New Customer</h2>
}
else
{
    <h2>Editing @Model.Name</h2>
}

@using (Html.BeginForm("Save", "Customers"))
{
    @Html.ValidationSummary(true, "Please fix the following errors.")

    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
    ///Release date
    DateTime birthDate = DateTime.Now;

    if(Model != null)
    {
        birthDate = Model.Birthdate;
    }
    <div class="form-group">
        @Html.LabelFor(m => m.Birthdate)
        @Html.TextBoxFor(m => m.Birthdate, birthDate.ToString("d MMM yyyy", new System.Globalization.CultureInfo("en-EN")), new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Birthdate)
    </div>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.IsSubcribedToNewsletter) Subcribed to Newsletter?
        </label>
    </div>
    if ((Model == null) || (Model.Id == 0))
    {
        @Html.Hidden("Id", 0);
    }
    else
    {
        @Html.HiddenFor(c => c.Id)
    }
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

@section scripts 
{
    @Scripts.Render("~/bundles/jqueryval");
}

Filmy/Views/Customers/Details.cshtml
@model Filmy.Models.Customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

    DateTime minDate = DateTime.MinValue;
    var twoLetters = string.Empty;
    twoLetters += Model.Name[0];
    twoLetters += Model.Name[1];
    twoLetters = twoLetters.ToUpper();

    int customerId = Model.Id;
}

<style>
    body {
        background-color: #EDEDF4;
    }
</style>

<h2 id="circled-name">@twoLetters</h2>
<h2>@Model.Name</h2>
@if (Model.Birthdate != minDate)
{
    <h4>@Html.Label(Model.Birthdate.ToString("d MMM yyyy"))</h4>
}

<div class="section-title">
    <h2>Movies</h2>
</div>
<div class="row">
@if (Model.MovieLibrary != null)
{
    foreach (var movie in Model.MovieLibrary)
    {
    <div class="column">
        <div class="img-wrap" data-id="@movie.Id">
            <img class="close" src="\Content\Images\close_btn.png" width="60" height="60" />
            <img src="@movie.Image" width="310" height="384">
        </div>
    </div>
    }
}
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.img-wrap .close').on('click', function () {
                var target = $(this).closest('.img-wrap').find('img');
                var id = $(this).closest('.img-wrap').data('id');
                target.fadeOut('200', function () {
                    target.remove();
                });
            $.ajax({
                url: '@Url.Action("DeleteMovie", "Customers")',
                type: 'post',
                cache: false,
                async: true,
                data: { id: id, customerId: @customerId },
            });
            });

        });
    </script>
}

Filmy/Views/Customers/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["message"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["message"]
    </div>
}

<div class="section-title">
    <h2 style="background-color: white">Customers</h2>
</div>

@Html.ActionLink("New Customer", "New", "Customers", new { @class = "btn btn-primary" })

<br />

<table id="customers" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Customer</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {

            $("#customers").DataTable({
                ajax: {
                    url: "/api/customers",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "Name",
                        render: function (data, type, customer) {
                            return "<a href='/customers/details/" + customer.Id + "'>" + customer.Name + "</a>";
                        }
                    },
                    {
                        data: "Id",
                        render: function (data) {
                            return "<button class='btn-link js-delete' data-customer-id=" + data + ">Delete</button>";
                        }
                    },
                    {
                        render: function (name, type, customer) {
                            return "<a href='/customers/edit/" + customer.Id + "'>" + "Edit" + "</a>";
                        }
                    },
                ]
            });

            $("#customers").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this customer?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/customers/" + button.attr("data-customer-id"),
                            method: "DELETE",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
}